from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator


StrategyFamily = Literal[
    "market_making",
    "statistical_arbitrage",
    "cross_venue_arbitrage",
    "mean_reversion",
    "trend_following",
    "volatility",
    "execution",
    "event_driven",
]

MarketRegime = Literal[
    "trending_up",
    "trending_down",
    "range_bound",
    "high_volatility",
    "low_volatility",
    "event_driven",
    "mixed",
    "unknown",
]

Horizon = Literal[
    "microseconds",
    "milliseconds",
    "seconds",
    "minutes",
    "hours",
]


class StrategyMetrics(BaseModel):
    """Evidence supplied by the strategy owner, not generated by Jev."""

    net_return: float | None = None
    sharpe: float | None = None
    oos_sharpe: float | None = None
    max_drawdown: float | None = Field(default=None, ge=0)
    win_rate: float | None = Field(default=None, ge=0, le=1)
    latency_ms: float | None = Field(default=None, ge=0)
    slippage_bps: float | None = Field(default=None, ge=0)
    capacity_usd: float | None = Field(default=None, ge=0)
    walk_forward_passes: int | None = Field(default=None, ge=0)
    regime_consistency: float | None = Field(default=None, ge=0, le=1)
    sample_start: str | None = None
    sample_end: str | None = None


class StrategyProfile(BaseModel):
    id: str = Field(pattern=r"^[a-zA-Z0-9][a-zA-Z0-9_.-]{1,63}$")
    name: str
    description: str
    family: StrategyFamily
    asset_classes: list[str] = Field(min_length=1)
    symbols: list[str] = Field(default_factory=lambda: ["*"])
    venues: list[str] = Field(default_factory=lambda: ["generic"])
    horizons: list[Horizon] = Field(min_length=1)
    regimes: list[MarketRegime] = Field(min_length=1)
    min_capital_usd: float = Field(default=0, ge=0)
    max_acceptable_latency_ms: float | None = Field(default=None, gt=0)
    risk_level: int = Field(default=3, ge=1, le=5)
    requires_live_order_book: bool = False
    strengths: list[str] = Field(default_factory=list)
    weaknesses: list[str] = Field(default_factory=list)
    metrics: StrategyMetrics = Field(default_factory=StrategyMetrics)
    source: str = "user-supplied"
    production_ready: bool = False
    enabled: bool = True

    def compact_choice_description(self) -> dict[str, Any]:
        return {
            "family": self.family,
            "description": self.description,
            "asset_classes": self.asset_classes,
            "symbols": self.symbols,
            "venues": self.venues,
            "horizons": self.horizons,
            "regimes": self.regimes,
            "risk_level": self.risk_level,
            "max_latency_ms": self.max_acceptable_latency_ms,
            "min_capital_usd": self.min_capital_usd,
            "strengths": self.strengths[:3],
            "weaknesses": self.weaknesses[:3],
            "evidence": self.metrics.model_dump(exclude_none=True),
            "production_ready": self.production_ready,
        }


class MarketSnapshot(BaseModel):
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    asset_class: str | None = None
    symbol: str | None = None
    venue: str | None = None
    regime: MarketRegime = "unknown"
    volatility_percentile: float | None = Field(default=None, ge=0, le=1)
    spread_bps: float | None = Field(default=None, ge=0)
    order_book_depth_usd: float | None = Field(default=None, ge=0)
    volume_24h_usd: float | None = Field(default=None, ge=0)
    funding_rate: float | None = None
    observed_latency_ms: float | None = Field(default=None, ge=0)
    source: str = "user-or-agent"

    @model_validator(mode="after")
    def ensure_timezone(self) -> "MarketSnapshot":
        if self.timestamp.tzinfo is None:
            self.timestamp = self.timestamp.replace(tzinfo=timezone.utc)
        return self


class UserConstraints(BaseModel):
    asset_class: str | None = None
    symbol: str | None = None
    venue: str | None = None
    capital_usd: float | None = Field(default=None, gt=0)
    available_latency_ms: float | None = Field(default=None, ge=0)
    max_drawdown: float | None = Field(default=None, ge=0)
    max_risk_level: int | None = Field(default=None, ge=1, le=5)
    allowed_families: list[StrategyFamily] | None = None
    excluded_models: list[str] = Field(default_factory=list)
    require_production_ready: bool = False


class RouteRequest(BaseModel):
    query: str = Field(min_length=3, max_length=12_000)
    market: MarketSnapshot | None = None
    constraints: UserConstraints = Field(default_factory=UserConstraints)
    request_id: str | None = None


class Classification(BaseModel):
    family: StrategyFamily
    horizon: Horizon
    regime: MarketRegime
    risk_score: float = Field(ge=0, le=4)
    abstain_probability: float = Field(ge=0, le=1)
    requires_live_data_probability: float = Field(ge=0, le=1)
    confidence: float = Field(ge=0, le=1)


class Selection(BaseModel):
    choice: str
    confidence: float = Field(ge=0, le=1)
    probabilities: dict[str, float]


class Alternative(BaseModel):
    model_id: str
    name: str
    probability: float


class RouteResponse(BaseModel):
    request_id: str
    status: Literal["selected", "no_trade", "review_required"]
    selected_model: StrategyProfile | None = None
    confidence: float = Field(ge=0, le=1)
    classification: Classification
    alternatives: list[Alternative] = Field(default_factory=list)
    reason_codes: list[str] = Field(default_factory=list)
    scanned_models: int
    eligible_models: int
    backend: str
    execution_allowed: bool = False
    paper_test_required: bool = True
    warning: str = (
        "Research router only. It selects from the connected registry and does "
        "not predict profit, provide personalized financial advice, or execute trades."
    )
